### ISSUE TITLE
Air Alarm in Theater's entrance

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7104] opened 2018-03-15 02:47 UTC
In-Game report from dudeinyourbackyard:
Server info: 27288 (Hippie Station)

>General description of the issue
There's an air alarm just kind of floating in the entrance to the theater wardrobe room.

>What you expected to happen
For there to not be an air alarm floating in the entrance to the theater wardrobe room.

>What actually happened
There was an air alarm floating in the entrance to the theater wardrobe room.

>Steps to reproduce if possible
Open the airlock to the theater wardrobe room.

**Comment by GuyonBroadway** [comment] 2018-03-15 02:56
dupe of https://github.com/HippieStation/HippieStation/issues/7043

**Closed as completed by GuyonBroadway** 2018-03-15 02:56 UTC
