### ISSUE TITLE
fuckn extinguishers no longer damage slime

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7190] opened 2018-03-20 18:10 UTC
In-Game report from glordqtinkle:
Server info: 27403 (Hippie Station)

>General description of the issue
WHATS UP WITH THAAAAAAAAAAAAAAAAT

>What you expected to happen
WHAT IS THE DEAL

>What actually happened
WITH

>Steps to reproduce if possible
THAAAAAAAAAAAAAAAAAAAAAAAAAT

**Comment by praisenarsie** [comment] 2018-03-23 17:04
is this a result of chempiles

**Comment by GuyonBroadway** [comment] 2018-03-23 17:06
Nah I think its a thing on tg too.

**Comment by geylard** [comment] 2018-03-28 02:07
oh, extinguishers no longer chill things. slimes are pretty much unkillable now though.

**Comment by Jujumatic** [comment] 2018-03-29 09:10
Fixing it in #7336 

Though it seems monkey cubes won't expand with the fire extinguisher either. wtf

**Comment by JohnGinnane** [comment] 2018-04-09 21:32
This is caused by us adding in cryogenic_fluid

**Comment by JohnGinnane** [comment] 2018-04-09 21:32
Related to https://github.com/HippieStation/HippieStation/issues/7347

**Comment by JohnGinnane** [comment] 2018-06-21 17:39
Fixed by https://github.com/HippieStation/HippieStation/pull/7616

**Closed as completed by JohnGinnane** 2018-06-21 17:39 UTC
