### ISSUE TITLE
rapid pipe dispensers cannot dispense disposal pipes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7433] opened 2018-04-02 19:27 UTC
In-Game report from bubberduckydducker:
Server info: 27692 (Hippie Station)

>General description of the issue
rapid pipe dispenser can't dispense disposal pipes

>What you expected to happen
i wanted a disposal pipe, so i pressed the disposal pipe mode...

>What actually happened
it showed me the transit tube mode instead, when i tried to revert back into disposal pipe mode it just showed a blank screen

>Steps to reproduce if possible

find a rapid pipe dispenser and try to spawn a disposal pipe, you'll see that you cannot because of the buggy menu fucking it all over for you 
 
pls fix or else no more pipe loops for this sad lad : - (

**Comment by JohnGinnane** [comment] 2018-04-02 19:33
Duplicate of https://github.com/HippieStation/HippieStation/issues/7111

**Comment by JohnGinnane** [comment] 2018-04-02 19:33
Should probably look at fixing this though

**Closed as completed by JohnGinnane** 2018-04-02 19:33 UTC
