### ISSUE TITLE
dark blue slime extract

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6918] opened 2018-03-03 22:34 UTC
In-Game report from rapidgokhandrum:
Server info: 27000 (Hippie Station)

>General description of the issue

it doesnt release cold gas like it did before
>What you expected to happen

it should release something like freon when injected with plasma but it does not
>What actually happened
it just disappears

>Steps to reproduce if possible

**Comment by Carbonhell** [comment] 2018-07-08 15:31
Duplicate of #6781

**Closed as completed by Carbonhell** 2018-07-08 15:31 UTC
