### ISSUE TITLE
If you cancel disassembling a table it messes with item placement on that table

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#4745] opened 2017-11-12 13:20 UTC
Not sure if it's an upstream issue or not

Steps to reproduct:

1. Use a screwdriver on a table
2. Move away to stop the disassembly before it completes
3. Try to place an item on the table

See example below, it keeps placing the item at the bottom of the table, maybe sprite offsets or something, not sure.

Left table: Untouched
Right table: Started disassembly but cancelled

![image](https://user-images.githubusercontent.com/3355198/32699363-3b119cf0-c7ac-11e7-8cc2-c565ea903388.png)

**Comment by JohnGinnane** [comment] 2017-11-12 18:23
Just did a quick test and it's not an upstream issue

**Comment by Carbonhell** [comment] 2018-08-17 14:43
Cannot reproduce, it was probably fixed long ago? Closing

**Closed as completed by Carbonhell** 2018-08-17 14:43 UTC
