### ISSUE TITLE
chem dispencers turn invisible when the power is turned off

### ISSUE THREAD

**Issue by lolmemelord123** [HippieStation/HippieStationdeprecated2020#8877] opened 2018-08-31 14:26 UTC
i noticed this multiple times always when the chemistry apc is low and it automaticly turns off. the chem dispencers then turn invisible and im not able to interact with them

**Comment by Carbonhell** [comment] 2018-08-31 15:17
Duplicate of #8832 . We're sorry for the troubles, it will be fixed soon.

**Closed as completed by Carbonhell** 2018-08-31 15:17 UTC
