### ISSUE TITLE
I CANT CLICK OB PEOPLE WHEN THEYRE LYING DOWN

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4734] opened 2017-11-11 22:13 UTC
In-Game report from spankmaster:
Server info: 24304 (Hippie Station)

>IF I STUN SOMEONE I CANT INTERACT WITH THEM OR CLICK ON THEM

>CLICKJ

>COULDNT CLICK
>STUN SOMEONE AND TRY TO HIT THEM , THIS SHIT IS RUINING MY FUCKIN ROUNDS

**Comment by PopNotes** [comment] 2017-11-11 22:16
lmao owned

**Comment by GuyonBroadway** [comment] 2017-11-11 22:19
What is yer byond version? What is yer Internext Explorer version? When was the last time you updated windows?

**Comment by Blute1** [comment] 2017-11-12 00:12
this bug is a duplicate of #4572

**Comment by Spankmaster1066** [comment] 2017-11-14 15:26
We need to fix this bullshit, I can't count on two hands the number of times I've just barely managed to get a stun off on someone who is attacking me and find myself unable to interact with their body at all, standing there like a dipshit with my weapon in hand clicking frantically until my opponent stands back up, knocks me over, and rapes my soul physically.

**Comment by Carbonhell** [comment] 2018-01-18 18:23
As dong said,duplicated. The other one is explained better,closing this

**Closed as completed by Carbonhell** 2018-01-18 18:23 UTC
Labels: Needs Reproducing/Testing
