### ISSUE TITLE
inconsistent reee

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6118] opened 2018-01-21 20:09 UTC
In-Game report from glordqtinkle:
Server info: 26033 (Hippie Station)

>General description of the issue
ion gun destroys the charge of batons and tazer guns but not actual tazers? reeeeeeeeeeeeeeeee

>What you expected to happen
REEEEEEe

>What actually happened
REEEEEEEEEEEEEEEE

>Steps to reproduce if possible

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by GuyonBroadway** [comment] 2018-01-21 20:13
What the fuck do you mean by "actual tasers"

**Comment by geylard** [comment] 2018-01-21 20:15
stun guns you big bully

**Comment by JohnMcLaime** [comment] 2018-01-21 22:23
It barely affects stunbatons too.

**Comment by JohnGinnane** [comment] 2018-02-05 13:56
Duplicate of #5910

**Closed as completed by JohnGinnane** 2018-02-05 13:56 UTC
